team_index:
    path:     /
    defaults: { _controller: "FootballBundle:Team:index" }
    methods:  GET

team_show:
    path:     /{id}/show
    defaults: { _controller: "FootballBundle:Team:show" }
    methods:  GET

team_new:
    path:     /new
    defaults: { _controller: "FootballBundle:Team:new" }
    methods:  POST

team_edit:
    path:     /{id}/edit
    defaults: { _controller: "FootballBundle:Team:edit" }
    methods:  POST

team_delete:
    path:     /{id}/delete
    defaults: { _controller: "FootballBundle:Team:delete" }
    methods:  DELETE
