FootballBundle\Entity\League:
    type: entity
    table: leagues
    repositoryClass: FootballBundle\Repository\LeagueRepository

    oneToMany:
        teams:
            targetEntity: Team
            mappedBy: league

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
